- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.xtextgenerator/src/com/ge/research/sadl/xtextgenerator/SerializerDisablingStandardLanguage.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/GenerateSADL.mwe2
Moved the custom MWE fragment to separate plug-in since it has to be built
before the plug-in containing the workflow.
> Fixed maven build.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/AbstractSADLParsingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/model/SadlModelProcessorTestTypeChecking.xtend
This PR is only a proposal for #132 .
This does not fix the third failing test case but creates an implicit
model instance on demand. And this is just a proposal anyway.
> GH-132: Added a convenient way to automatically generate implicit model.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/editor/CopyQualifiedNameServiceTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/plugin.xml
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/SADLUiModule.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/editor/SadlCopyQualifiedNameService.java
> GH-134 Fixed separator when copying URI from editor and from Outline.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/naming/GH_145_IncorrectValueConverterServiceOutput.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/ValueConverterService.xtend
> GH-145: Fixed value converter service. Added tests.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/imports/GH_147_ImportScopeOnBrokenAST.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
Occurred when import scope was created with broken AST. Added test.
> GH-147: Fixed NPE in scope provider.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/META-INF/MANIFEST.MF
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/GH_162_ImplicitModelContentProviderTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/META-INF/MANIFEST.MF
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/GH_162_ImplicitModelContentProviderPluginTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/Run SADL IDE (Eclipse) jdk 1.8 (ASSERT).launch
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/Run SADL IDE (Eclipse) jdk 1.8 (OS).launch
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/Run SADL IDE (Eclipse) jdk 1.8 (debug).launch
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/SADLUiModule.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/plugin.xml
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/schema/sadl_implicit_mode_fragment_provider.exsd
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlImplicitModelContentProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlImplicitModelFragmentProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlModelProcessor.java
> GH-162: Added support to generate implicit SADL model based on contributed fragments

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/preferences/SadlPreferenceStoreAccess.xtend
> Fixed preference store initialization issue in case of multiple DSLs.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelValidator.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/GH_164_TypeCheckInfoTest.xtend
> GH-164: Added hashCode implementation to TypeCheckInfo.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/contentassist/SadlOntologyContextTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/CompositeModelProcessor.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/IModelProcessor.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlOntologyHelper.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlOntologyHelper.xtend
> Extended model processor API to be able to validate an individual SADL

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/GrammarContextIDsTest.xtend
> GH-176: Fixed ignored test cases.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/GrammarContextIDsTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/META-INF/MANIFEST.MF
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/contentassist/AbstractSadlContentAssistTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/contentassist/SadlContentAssistTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/contentassist/SadlOntologyContextTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/contentassist/IOntologyContextProvider.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/contentassist/ProposalProviderFilterProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/contentassist/SadlOntologyContextProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/CompositeModelProcessor.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlOntologyHelper.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlOntologyHelper.xtend
Also fixed a couple of failing test cases and enabled ignored tests.
> GH-181: Made sure that the correct model processor is used for ontology contexts

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.feature/feature.xml
> GH-193: Fixed update site issue. Added missing JUnit dependency.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/plugin.xml
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/external/ExternalEmfBuilderParticipant.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/external/ExternalEmfUIResourceServiceProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/markers/SadlMarkerStartup.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/external/ExternalEmfResource.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/external/ExternalEmfResourceGenerator.xtend
~<b>Not yet ready to merge.</b>~
~Work in progress...~
Done, ready to merge.
@svenefftinge, could you please look into the initial changes? Thanks in advance!
> GH-182 Registered generator for external SADL resources.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ide/src/com/ge/research/sadl/ide/lsp/inference/SadlInferencer.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/AbstractLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/AbstractSADLParsingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/AbstractSadlTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/SADLNoopModelProcessorsInjectorProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/helpers/SadlTestProjectStructureInitializer.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/lsp/AbstractSadlLanguageServerTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/lsp/SadlColoringTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/SadlLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui.tests/src/com/ge/research/sadl/ui/tests/contentassist/AbstractSadlContentAssistTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlImplicitModelContentProvider.xtend
> GH-210, GH-211: Cleaned up base test classes and implicit model content provider

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/imports/DependencyTraverserHelperTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/utils/DependencyTraverserHelper.xtend
> Fixed cyclic dependency validation.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.feature/feature.xml
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/markers/GH_216_ExternalMarkersDoesNotPreserveLFs.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/META-INF/MANIFEST.MF
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarkerDeserializerService.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarkerLocationProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/markers/SadlMarkerSeverityMapper.xtend
Task: #216.
Closes #216.
Switched from default DOM to Jsoup.
> GH-216: Preserved CR/LFs when parsing XML for external markers.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/query/SadlQueryHelperTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/query/SadlQueryHelper.xtend
> GH-219: Added helper to be able to retrieve a query by its name.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/SadlLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
> GH-215: Fixed scoping for necessary and sufficient (only if).

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
These are the required changes to be able to support https://github.com/GEGlobalResearch/requirements/issues/40 .
> Updated API to be able to extend scoping from downstream grammars.

- .travis.yml
- appveyor.yml
> GH-236: Configured Linux, OS X and Windows CI.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/SadlLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
> GH-256: Fixed a couple of scoping issues.

- README.md
> GH-244: Added the build-badges to the main README.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/model/SadlModelProcessorTypeCheckingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/quickfix/SADLQuickfixProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/query/SadlQueryHelper.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/AmbiguousNameErrorEObjectDescription.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/ErrorAddingLinkingService.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
Closes #271.
@nbachman, @crapo. Please review the changes, I look forward to the feedbacks.
> GH-271 Fixed quick fixes for ambiguous name errors

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
The error occurred when the Eclipse project was not copied into the
Eclipse workspace during the import phase.
> GH-288: Fixed the implicit model and built-in function URI calculation.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/handlers/RunInference.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/handlers/SadlActionHandler.java
Without a context (the resource URI inside the target project), the
preferences could not be retrieved. The workspace-specific one was
used instead.
Task: https://github.com/crapo/sadlos2/issues/290
> GH-290: Fixed a project-specific preferences issue in the handler.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java
Also made the root URI calculation OS independent.
Closes: #335.
> GH-335: Fixed injection issue when collecting keywords.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/AbstractLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/SadlLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
> GH-344: Adjusted the `EquationStatement` scoping to the latest grammar state.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/EquationStatementLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/scoping/SadlLinkingTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/utils/SadlASTUtils.xtend
> GH-344: Fixed the scoping in the equation statements.

- README.md
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.xtextgenerator/src/com/ge/research/sadl/xtextgenerator/JFlexLoader.xtend
> GH-364: Fixed the JFlex download URL. 

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlInferenceProcessor.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/ISadlInferenceProcessor.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/SadlInferenceProcessorProvider.xtend
Downstream languages can contribute customized inference processors.
Closes #367.
> GH-367: From now on, inference processors can be filtered by extension.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/owl2sadl/OwlToSadl.java
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/pom.xml
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/SadlKeywordsTest.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.tests/src/com/ge/research/sadl/tests/owl2sadl/OwlToSadlTest.java
Closes #369.
Closes #370.
Ignored a failing test case. See #372.
I have verified this with
```
git clean -ffxqd \
&& cd sadl3/com.ge.research.sadl.parent/ \
&& mvn clean verify
```
And also by running the tests from Eclipse IDE.
> Fixed the Maven test issues from the CLI. Added tests for the SADL keywords.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/scoping/SADLScopeProvider.xtend
Closes #376.
@crapo, can you please verify the proposed changes? Is there a chance we can transform [your example](https://github.com/crapo/sadlos2/files/3393729/SemanticConstraintsExample.sadl.txt) into a test case?
Please note, before I started to work on this, I ran the build on the `AugmentedTypes` branch. I had test failures in the `SadlServer Implementation`. I did not know this exists 😊
```
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running com.ge.research.sadl.server.server.TestSadlServerPEOnShapes
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/com.ge.res …
```
> GH-376: Fixed the scoping for external equations.

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/processing/IModelProcessor.xtend
- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/validation/ResourceValidator.xtend
> Hook for customizing the pref values provider

- sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.ui/src/com/ge/research/sadl/ui/syntaxcoloring/SadlSemanticHighlightingCalculator.xtend
Use the scope provider to remap a SADL resource
to its definition. Otherwise, isExternal call
give false negative answer and break the highlighting.
> Fixed the highlighting for externals.
